[package]
name = "mailstrom"
version = "0.4.0-unstable"
description = "Email sender"
authors = ["Mike Dilger <mike@optcomp.nz>"]
readme = "README.md"
repository = "https://github.com/mikedilger/mailstrom"
documentation = "https://mikedilger.github.io/mailstrom"
license = "MIT OR Apache-2.0"
keywords = [ "email" ]

[dev-dependencies]
env_logger = "0.3"

[dependencies]
uuid = { version = "0.4", features = [ "v4" ] }
email-format = "0.4"
resolv = ">=0.1.3"
lettre = { git = "https://github.com/lettre/lettre", rev="99538201744b8cf7eae1a5b6e24643583703a8e2" }
log = "0.3"
serde = "0.9"
serde_derive = "0.9"
