[package]
name = "mailstrom"
version = "0.4.0-unstable"
description = "Email sender"
authors = ["Mike Dilger <mike@optcomp.nz>"]
readme = "README.md"
repository = "https://github.com/mikedilger/mailstrom"
documentation = "https://mikedilger.github.io/mailstrom"
license = "MIT OR Apache-2.0"
keywords = [ "email" ]

[dev-dependencies]
env_logger = "0.3"

[dependencies]
uuid = { version = "0.4", features = [ "v4" ] }
email-format = "0.4"
trust-dns-resolver="0.6"
lettre = { git = "https://github.com/lettre/lettre", rev="4f41eef9362fa8fdb31d01e16b5c1a7e5e50d7e4" }
log = "0.3"
serde = "1.0"
serde_derive = "1.0"
